### ISSUE TITLE
Does this handle imports?

### ISSUE THREAD

**Issue by edeesims** [Neos21/in-browser-sass#1]
I have a scss file that looks similar to this

```scss
@import './base';

.foo {
    color: bar;
}
```

I am getting `undefined` in my style tag.
